force-app/main/default/objects/InventoryOutOrder__c/InventoryOutOrder__c.object-meta.xml
<CustomObject>
    <label>본사출고</label>
    <pluralLabel>Inventory Out Orders</pluralLabel>
    <nameField>
        <label>Inventory Out Order No</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InventoryOutOrder__c/fields/InventoryOutOrderDate__c.field-meta.xml
<CustomField>
    <fullName>InventoryOutOrderDate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>과거날짜 안됨</description>
    <label>Inventory Out Order Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/InventoryOutOrder__c/fields/NetAmount__c.field-meta.xml
<CustomField>
    <fullName>NetAmount__c</fullName>
    <label>Net Amount</label>
    <summarizedField>InventoryOutOrderLineItem__c.NetAmount__c</summarizedField>
    <summaryForeignKey>InventoryOutOrderLineItem__c.InventoryOutOrder__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/InventoryOutOrder__c/fields/PurchaseVendor__c.field-meta.xml
<CustomField>
    <fullName>PurchaseVendor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Purchase Vendor</label>
    <referenceTo>VendorPurchase__c</referenceTo>
    <relationshipName>Release</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InventoryOutOrderLineItem__c/InventoryOutOrderLineItem__c.object-meta.xml
<CustomObject>
    <label>본사출고상세</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InventoryOutOrderLineItem__c/fields/InventoryOutOrder__c.field-meta.xml
<CustomField>
    <fullName>InventoryOutOrder__c</fullName>
    <label>Inventory Out Order</label>
    <referenceTo>InventoryOutOrder__c</referenceTo>
    <relationshipLabel>Inventory Out Order LineItem</relationshipLabel>
    <relationshipName>ReleaseItem</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InventoryOutOrderLineItem__c/fields/NetAmount__c.field-meta.xml
<CustomField>
    <fullName>NetAmount__c</fullName>
    <formula>NetPrice__c * Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InventoryOutOrderLineItem__c/fields/NetPrice__c.field-meta.xml
<CustomField>
    <fullName>NetPrice__c</fullName>
    <description>변경가능 (공급단가(세액제외))</description>
    <label>Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InventoryOutOrderLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Inventory Out Order LineItem</relationshipLabel>
    <relationshipName>Inventory_Out_Order_LineItem</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InventoryOutOrderLineItem__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InventoryOutOrderLineItem__c/fields/SkuOption2__c.field-meta.xml
<CustomField>
    <fullName>SkuOption2__c</fullName>
    <label>Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SkuOption2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <pluralLabel>Products</pluralLabel>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <displayFormat>P{00000}</displayFormat>
    <label>Product Code</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PurchaseVendor__c.field-meta.xml
<CustomField>
    <fullName>PurchaseVendor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Purchase Vendor</label>
    <referenceTo>VendorPurchase__c</referenceTo>
    <relationshipName>Product</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VendorPurchase__c/VendorPurchase__c.object-meta.xml
<CustomObject>
    <label>매입거래처</label>
    <pluralLabel>Purchase Vendors</pluralLabel>
    <nameField>
        <label>Purchase Vendor Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/SkuOption2.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>12.3</fullName>
    </customValue>
    <customValue>
        <fullName>12.4</fullName>
    </customValue>
    <customValue>
        <fullName>12.5</fullName>
    </customValue>
    <masterLabel>SkuOption2</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GfWarehouseInController.cls
public with sharing class GfWarehouseInController {

    @AuraEnabled
    public static WrapperPurchaseOrder getOrder(String recordId) {
        InventoryOutOrder__c order = [
            SELECT Id, Name, InventoryOutOrderDate__c, PurchaseVendor__c, PurchaseVendor__r.Name, NetAmount__c
            FROM InventoryOutOrder__c 
            WHERE Id = :recordId
            LIMIT 1
        ];
        return new WrapperPurchaseOrder(order);
    }

    @AuraEnabled
    public static List<WrapperPurchaseOrderItem> getOrderItems(String recordId) {
        List<InventoryOutOrderLineItem__c> items = [
            SELECT Id, Name, Product__c, Product__r.ProductCode__c, Product__r.Name, NetPrice__c, Quantity__c, 
                    SkuOption1__c, SkuOption2__c, SkuOption3__c, InventoryOutOrder__c
            FROM InventoryOutOrderLineItem__c
            WHERE InventoryOutOrder__c = :recordId
        ];

        List<WrapperPurchaseOrderItem> wrappedItems = new List<WrapperPurchaseOrderItem>();
        for (InventoryOutOrderLineItem__c item : items) {
            wrappedItems.add(new WrapperPurchaseOrderItem(item));
        }
        return wrappedItems;
    }

    public class WrapperPurchaseOrder {
        @AuraEnabled public String id;
        @AuraEnabled public String name;
        @AuraEnabled public Date inventoryOutOrderDate;
        @AuraEnabled public String purchaseVendor;
        @AuraEnabled public Decimal netAmount;

        public WrapperPurchaseOrder(InventoryOutOrder__c order) {
            this.id = order.Id;
            this.name = order.Name;
            this.inventoryOutOrderDate = order.InventoryOutOrderDate__c;
            this.purchaseVendor = order.PurchaseVendor__r.Name;
            this.netAmount = order.NetAmount__c;
        }
    }

    public class WrapperPurchaseOrderItem {
        @AuraEnabled public String id;
        @AuraEnabled public String productCode;
        @AuraEnabled public String name;
        @AuraEnabled public Decimal netPrice;
        @AuraEnabled public Decimal quantity;
        @AuraEnabled public String skuOption1;
        @AuraEnabled public String skuOption2;
        @AuraEnabled public String skuOption3;

        public WrapperPurchaseOrderItem(InventoryOutOrderLineItem__c item) {
            this.id = item.Id;
            this.productCode = item.Product__r.ProductCode__c;
            this.name = item.Product__r.Name;
            this.netPrice = item.NetPrice__c;
            this.quantity = item.Quantity__c;
            this.skuOption1 = item.SKUOption1__c;
            this.skuOption2 = item.SKUOption2__c;
            this.skuOption3 = item.SKUOption3__c;
        }
    }
}