force-app/main/default/objects/GfAmsGoods__c/GfAmsGoods__c.object-meta.xml
<CustomObject>
    <label>본사 상품 Old</label>
    <nameField>
        <label>Goods Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GfAmsGoods__c/fields/Barcode__c.field-meta.xml
<CustomField>
    <fullName>Barcode__c</fullName>
    <description>바코드</description>
    <label>Barcode</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GfAmsGoods__c/fields/BasePrice__c.field-meta.xml
<CustomField>
    <fullName>BasePrice__c</fullName>
    <description>기준 단가</description>
    <label>Base Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GfAmsGoods__c/fields/BoxAcquisitionQuantities__c.field-meta.xml
<CustomField>
    <fullName>BoxAcquisitionQuantities__c</fullName>
    <description>박스 입수수량</description>
    <label>Box Acquisition Quantities</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GfAmsGoods__c/fields/BoxBarcode__c.field-meta.xml
<CustomField>
    <fullName>BoxBarcode__c</fullName>
    <description>박스 바코드</description>
    <label>Box Barcode</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GfAmsGoods__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>분류</description>
    <label>Class</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GfAmsGoods__c/fields/GoodsNameEnglish__c.field-meta.xml
<CustomField>
    <fullName>GoodsNameEnglish__c</fullName>
    <description>상품 이름(English)</description>
    <label>Goods Name English</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GfAmsGoods__c/fields/GoodsShortName__c.field-meta.xml
<CustomField>
    <fullName>GoodsShortName__c</fullName>
    <description>상품 단축 명</description>
    <label>Goods Short Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GfAmsGoods__c/fields/GoodsType__c.field-meta.xml
<CustomField>
    <fullName>GoodsType__c</fullName>
    <description>상품 유형</description>
    <label>Goods Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/GfAmsGoods__c/fields/GraceAPrice__c.field-meta.xml
<CustomField>
    <fullName>GraceAPrice__c</fullName>
    <description>A 등급가</description>
    <label>GraceAPrice</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GfAmsGoods__c/fields/GraceBPrice__c.field-meta.xml
<CustomField>
    <fullName>GraceBPrice__c</fullName>
    <description>B 등급가</description>
    <label>GraceBPrice</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GfAmsGoods__c/fields/GraceCPrice__c.field-meta.xml
<CustomField>
    <fullName>GraceCPrice__c</fullName>
    <description>C 등급가</description>
    <label>GraceCPrice</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GfAmsGoods__c/fields/GraceDPrice__c.field-meta.xml
<CustomField>
    <fullName>GraceDPrice__c</fullName>
    <description>D 등급가</description>
    <label>GraceDPrice</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GfAmsGoods__c/fields/GraceEPrice__c.field-meta.xml
<CustomField>
    <fullName>GraceEPrice__c</fullName>
    <description>E 등급가</description>
    <label>GraceEPrice</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GfAmsGoods__c/fields/GraceFPrice__c.field-meta.xml
<CustomField>
    <fullName>GraceFPrice__c</fullName>
    <description>F 등급가</description>
    <label>GraceFPrice</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GfAmsGoods__c/fields/GraceGPrice__c.field-meta.xml
<CustomField>
    <fullName>GraceGPrice__c</fullName>
    <description>G 등급가</description>
    <label>GraceGPrice</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GfAmsGoods__c/fields/GraceHPrice__c.field-meta.xml
<CustomField>
    <fullName>GraceHPrice__c</fullName>
    <description>H 등급가</description>
    <label>GraceHPrice</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GfAmsGoods__c/fields/GraceIPrice__c.field-meta.xml
<CustomField>
    <fullName>GraceIPrice__c</fullName>
    <description>I 등급가</description>
    <label>GraceIPrice</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GfAmsGoods__c/fields/GraceJPrice__c.field-meta.xml
<CustomField>
    <fullName>GraceJPrice__c</fullName>
    <description>J 등급가</description>
    <label>GraceJPrice</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GfAmsGoods__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>활성 / 비활성</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GfAmsGoods__c/fields/Maker__c.field-meta.xml
<CustomField>
    <fullName>Maker__c</fullName>
    <description>제조사</description>
    <label>Maker</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GfAmsGoods__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <description>원산지</description>
    <label>Origin</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GfAmsGoods__c/fields/ParentGoods__c.field-meta.xml
<CustomField>
    <fullName>ParentGoods__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>대표상품</description>
    <label>Parent Goods</label>
    <referenceTo>GfAmsGoods__c</referenceTo>
    <relationshipName>Goods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GfAmsGoods__c/fields/PurchaseEndDate__c.field-meta.xml
<CustomField>
    <fullName>PurchaseEndDate__c</fullName>
    <description>발주 종료 일자</description>
    <label>Purchase End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/GfAmsGoods__c/fields/PurchaseLimit__c.field-meta.xml
<CustomField>
    <fullName>PurchaseLimit__c</fullName>
    <defaultValue>false</defaultValue>
    <description>본사 발주제한</description>
    <label>Purchase Limit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GfAmsGoods__c/fields/PurchaseLimitDateTime__c.field-meta.xml
<CustomField>
    <fullName>PurchaseLimitDateTime__c</fullName>
    <description>발주제한일시</description>
    <label>Purchase Limit Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/GfAmsGoods__c/fields/PurchaseLimitReason__c.field-meta.xml
<CustomField>
    <fullName>PurchaseLimitReason__c</fullName>
    <description>발주 제한사유</description>
    <label>Purchase Limit Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <label>없음</label>
            </value>
            <value>
                <fullName>Discontinued</fullName>
                <label>단종</label>
            </value>
            <value>
                <fullName>Suspend</fullName>
                <label>일시중단</label>
            </value>
            <value>
                <fullName>StockOut</fullName>
                <label>재고부족</label>
            </value>
            <value>
                <fullName>Others</fullName>
                <label>기타</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GfAmsGoods__c/fields/PurchaseLower__c.field-meta.xml
<CustomField>
    <fullName>PurchaseLower__c</fullName>
    <description>발주 하한 수량</description>
    <label>Purchase Lower</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GfAmsGoods__c/fields/PurchaseStartDate__c.field-meta.xml
<CustomField>
    <fullName>PurchaseStartDate__c</fullName>
    <description>발주 시작 일자</description>
    <label>Purchase Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/GfAmsGoods__c/fields/PurchaseUpper__c.field-meta.xml
<CustomField>
    <fullName>PurchaseUpper__c</fullName>
    <description>발주 상한 수량</description>
    <label>Purchase Upper</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GfAmsGoods__c/fields/PurchaseVenderType__c.field-meta.xml
<CustomField>
    <fullName>PurchaseVenderType__c</fullName>
    <description>유형</description>
    <label>Purchase Vender Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PurchaseVendorType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/GfAmsGoods__c/fields/PurchaseVendor__c.field-meta.xml
<CustomField>
    <fullName>PurchaseVendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>매입 거래처</description>
    <label>Purchase Vendor</label>
    <referenceTo>VendorPurchase__c</referenceTo>
    <relationshipName>Goods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GfAmsGoods__c/fields/SalesPrice__c.field-meta.xml
<CustomField>
    <fullName>SalesPrice__c</fullName>
    <description>권장 판매가</description>
    <label>Sales Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GfAmsGoods__c/fields/TaxType__c.field-meta.xml
<CustomField>
    <fullName>TaxType__c</fullName>
    <description>세금 구분</description>
    <label>Tax Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TaxType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/GfAmsGoods__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <description>단위</description>
    <label>Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>General</fullName>
        <label>일반상품</label>
    </customValue>
    <customValue>
        <fullName>Refrigerated</fullName>
        <label>냉장상품</label>
    </customValue>
    <customValue>
        <fullName>Frozen</fullName>
        <label>냉동상품</label>
    </customValue>
    <description>General;Refrigerated Frozen;</description>
    <masterLabel>Product Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/PurchaseVendorType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>HQ</fullName>
        <label>본사</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <label>타사</label>
    </customValue>
    <description>유형 [GfAmsVendorPurchase__c]</description>
    <masterLabel>Purchase Vendor Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/TaxType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Tax</fullName>
        <default>true</default>
        <label>과세</label>
    </customValue>
    <customValue>
        <fullName>TaxFree</fullName>
        <label>면세</label>
    </customValue>
    <description>세금 구분 [GfAmsGoods__c]</description>
    <masterLabel>Tax Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EA</fullName>
    </customValue>
    <customValue>
        <fullName>Kg</fullName>
    </customValue>
    <customValue>
        <fullName>Meter</fullName>
    </customValue>
    <customValue>
        <fullName>Liter</fullName>
    </customValue>
    <description>단위</description>
    <masterLabel>Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GfListViewController.cls
public with sharing class GfListViewController {
    
    @AuraEnabled
    public static List<WrapperClass> searchProducts(String searchValue) {
        String searchFilter = String.isNotBlank(searchValue) ? '%' + searchValue + '%' : '%';
        List<WrapperClass> recordList = new List<WrapperClass>();

         for(GfAmsGoods__c record : [
            SELECT  Id, Name, GoodsNameEnglish__c, GoodsShortName__c, PurchaseVenderType__c, GoodsType__c, Class__c, 
                    Barcode__c, ParentGoods__c, Maker__c, Origin__c, PurchaseVendor__c, BoxAcquisitionQuantities__c, BoxBarcode__c, 
                    TaxType__c, TaxRate__c, IsActive__c, Unit__c, SalesPrice__c, PurchaseStartDate__c, PurchaseEndDate__c, 
                    PurchaseLower__c, PurchaseUpper__c, PurchaseLimit__c, PurchaseLimitReason__c, PurchaseLimitDateTime__c, 
                    ReturnLimit__c, BasePrice__c, GraceAPrice__c, GraceBPrice__c, GraceCPrice__c, GraceDPrice__c, GraceEPrice__c, 
                    GraceFPrice__c, GraceGPrice__c, GraceHPrice__c, GraceIPrice__c, GraceJPrice__c
            FROM GfAmsGoods__c
            WHERE Name LIKE :searchFilter
            OR Barcode__c LIKE :searchFilter
            LIMIT 5
        ]) {
            recordList.add(new WrapperClass(record));
        }
        return recordList;
    }

    public class WrapperClass {
        @AuraEnabled public String id;
        @AuraEnabled public String productCode;
        @AuraEnabled public String productName;
        @AuraEnabled public Decimal productPrice;
        @AuraEnabled public String color;
        @AuraEnabled public String diameter;
        @AuraEnabled public String material;

        public WrapperClass() {}

        public WrapperClass(GfAmsGoods__c record) {
            this.id           = record.Id;
            this.productName  = record.Name;
            this.productCode  = record.Barcode__c;
            this.productPrice = record.BasePrice__c;
            this.color        = null;
            this.diameter     = null;
            this.material     = null;
        }
    }


}