force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <pluralLabel>Products</pluralLabel>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/BasePrice__c.field-meta.xml
<CustomField>
    <fullName>BasePrice__c</fullName>
    <label>Base Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/BaseUnit__c.field-meta.xml
<CustomField>
    <fullName>BaseUnit__c</fullName>
    <label>Base Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <displayFormat>P{00000}</displayFormat>
    <label>Product Code</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/ProductNameEng__c.field-meta.xml
<CustomField>
    <fullName>ProductNameEng__c</fullName>
    <label>Product Name(Eng)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/TaxRate__c.field-meta.xml
<CustomField>
    <fullName>TaxRate__c</fullName>
    <defaultValue>0.1</defaultValue>
    <label>Tax Rate</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/TaxType__c.field-meta.xml
<CustomField>
    <fullName>TaxType__c</fullName>
    <label>Tax Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TaxType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/TaxType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Tax</fullName>
        <default>true</default>
        <label>과세</label>
    </customValue>
    <customValue>
        <fullName>TaxFree</fullName>
        <label>면세</label>
    </customValue>
    <description>세금 구분 [GfAmsGoods__c]</description>
    <masterLabel>Tax Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GfProductSearchMoadlController.cls
public with sharing class GfProductSearchMoadlController {

    /**
     * 제품 서치 메소드
     * @param {String} searchValue 
     * @return  `List<WrapperClass>`
     */
    @AuraEnabled
    public static List<WrapperClass> searchProducts(String searchKeyWord) {
        List<WrapperClass> resultList = new List<WrapperClass>();
        try {
            String searchFilter = String.isNotBlank(searchKeyWord) ? '%' + searchKeyWord + '%' : '%';
    
            for(Product__c goods : [SELECT  Id, Name, ProductCode__c, ProductNameEng__c, BasePrice__c, BaseUnit__c, TaxType__c, TaxRate__c FROM Product__c 
                                            WHERE Active__c = true 
                                            AND (Name LIKE :searchFilter OR ProductCode__c LIKE :searchFilter) LIMIT 50]) 
            {
                resultList.add(new WrapperClass(goods));
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return resultList;
    }

    public class WrapperClass {
        @AuraEnabled public String productId;
        @AuraEnabled public String productName;
        @AuraEnabled public String productUrl; 
        @AuraEnabled public String productNameEng;
        @AuraEnabled public String productCode;
        @AuraEnabled public Decimal quantity;
        @AuraEnabled public Decimal productPrice;
        @AuraEnabled public Decimal totalPrice;
        @AuraEnabled public String unit;
        @AuraEnabled public String taxType;
        @AuraEnabled public Double taxRate;
        @AuraEnabled public String color;
        @AuraEnabled public String size;
        @AuraEnabled public String material;
        @AuraEnabled public Boolean isChecked;

        public WrapperClass() {}

        public WrapperClass(Product__c record) {
            this.productId       = record.Id;
            this.productName     = record.Name;
            this.productUrl      = makeRecordURL(record.Id);
            this.productNameEng  = record.ProductNameEng__c;
            this.productCode     = record.ProductCode__c;
            this.productPrice    = record.BasePrice__c;
            this.unit            = record.BaseUnit__c;
            this.taxType         = record.TaxType__c;
            this.taxRate         = record.TaxRate__c;
            this.quantity        = null;
            this.totalPrice      = null;
            this.size            = null;
            this.material        = null;
            this.isChecked       = false;
        }

        private String makeRecordURL(Id recordId) {
            return URL.getOrgDomainURL().toExternalForm() + '/' + recordId;
        }

    }

}