force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <pluralLabel>Products</pluralLabel>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <displayFormat>P{00000}</displayFormat>
    <label>Product Code</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PurchaseVendor__c.field-meta.xml
<CustomField>
    <fullName>PurchaseVendor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Purchase Vendor</label>
    <referenceTo>VendorPurchase__c</referenceTo>
    <relationshipName>Product</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/TaxRate__c.field-meta.xml
<CustomField>
    <fullName>TaxRate__c</fullName>
    <defaultValue>0.1</defaultValue>
    <label>Tax Rate</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PurchaseOrder__c/PurchaseOrder__c.object-meta.xml
<CustomObject>
    <label>본사발주</label>
    <pluralLabel>Purchase Orders</pluralLabel>
    <nameField>
        <label>Purchase Order Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PurchaseOrder__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PurchaseOrder__c/fields/OrderDate__c.field-meta.xml
<CustomField>
    <fullName>OrderDate__c</fullName>
    <description>Order Date</description>
    <label>Order Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PurchaseOrder__c/fields/OrderType__c.field-meta.xml
<CustomField>
    <fullName>OrderType__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NewOrder</fullName>
                <label>New Order</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PurchaseOrder__c/fields/PartnerId__c.field-meta.xml
<CustomField>
    <fullName>PartnerId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Partner__c</referenceTo>
    <relationshipLabel>Purchase Order</relationshipLabel>
    <relationshipName>Purchase_Order1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PurchaseOrder__c/fields/PurchaseVendor__c.field-meta.xml
<CustomField>
    <fullName>PurchaseVendor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Purchase Vendor</label>
    <referenceTo>VendorPurchase__c</referenceTo>
    <relationshipLabel>Purchase Order</relationshipLabel>
    <relationshipName>Purchase_Order1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PurchaseOrder__c/fields/RequestDate__c.field-meta.xml
<CustomField>
    <fullName>RequestDate__c</fullName>
    <label>Request Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PurchaseOrder__c/fields/RequestedBy__c.field-meta.xml
<CustomField>
    <fullName>RequestedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Requested By</description>
    <label>Requested By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RequestedByjQ7p</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PurchaseOrder__c/fields/RestofAddress__c.field-meta.xml
<CustomField>
    <fullName>RestofAddress__c</fullName>
    <label>Rest of Address</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PurchaseOrder__c/fields/SpecialTerms__c.field-meta.xml
<CustomField>
    <fullName>SpecialTerms__c</fullName>
    <description>Special Terms</description>
    <label>Special Terms</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PurchaseOrder__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <label>Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PurchaseOrderLineItem__c/PurchaseOrderLineItem__c.object-meta.xml
<CustomObject>
    <label>본사발주상세</label>
    <pluralLabel>Purchase Order Line Items</pluralLabel>
    <nameField>
        <displayFormat>OI{YY}{MM}{DD}{0000}</displayFormat>
        <label>PO Line Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PurchaseOrderLineItem__c/fields/OrderDate__c.field-meta.xml
<CustomField>
    <fullName>OrderDate__c</fullName>
    <formula>PurchaseOrder__r.OrderDate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PurchaseOrderLineItem__c/fields/OrderType__c.field-meta.xml
<CustomField>
    <fullName>OrderType__c</fullName>
    <formula>TEXT(PurchaseOrder__r.OrderType__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PurchaseOrderLineItem__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <formula>ProductId__r.ProductCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PurchaseOrderLineItem__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>ProductId</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PurchaseOrderLineItem__c/fields/PurchaseOrder__c.field-meta.xml
<CustomField>
    <fullName>PurchaseOrder__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>PurchaseOrder__c</referenceTo>
    <relationshipLabel>Purchase Order Line Item</relationshipLabel>
    <relationshipName>PurchaseOrderItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PurchaseOrderLineItem__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Order Quantity</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PurchaseOrderLineItem__c/fields/SkuOption1__c.field-meta.xml
<CustomField>
    <fullName>SkuOption1__c</fullName>
    <label>Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SkuOption1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PurchaseOrderLineItem__c/fields/SkuOption3__c.field-meta.xml
<CustomField>
    <fullName>SkuOption3__c</fullName>
    <label>Material</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SkuOption3</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PurchaseOrderLineItem__c/fields/Tax_Type__c.field-meta.xml
<CustomField>
    <fullName>Tax_Type__c</fullName>
    <label>Tax Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TaxType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PurchaseOrderLineItem__c/fields/TaxRate__c.field-meta.xml
<CustomField>
    <fullName>TaxRate__c</fullName>
    <defaultValue>0.1</defaultValue>
    <label>Tax Rate</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PurchaseOrderLineItem__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <formula>UnitPrice__c *  Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Order Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PurchaseOrderLineItem__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/SkuOption1.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Red</fullName>
    </customValue>
    <customValue>
        <fullName>Green</fullName>
    </customValue>
    <customValue>
        <fullName>Blue</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <masterLabel>SkuOption1</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SkuOption3.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Hiydrogel</fullName>
    </customValue>
    <customValue>
        <fullName>Silicon</fullName>
    </customValue>
    <masterLabel>SkuOption3</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/TaxType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Tax</fullName>
        <default>true</default>
        <label>과세</label>
    </customValue>
    <customValue>
        <fullName>TaxFree</fullName>
        <label>면세</label>
    </customValue>
    <description>세금 구분 [GfAmsGoods__c]</description>
    <masterLabel>Tax Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GfCreatePurchaseOrderModalController.cls
public with sharing class GfCreatePurchaseOrderModalController {

    private static final String PURCHASE_ORDER_OBJECT_NAME = 'PurchaseOrder__c';
    private static final String PURCHASE_ORDER_LINE_ITEM_OBJECT_NAME = 'PurchaseOrderLineItem__c';
    /**
     * 화면 생성시 초기 PickList Field 생성 메서드
     * @param {String} objectName 
     * @param {List<String>} pickListFieldName 
     * @return  `Map<String, Object>`
     * @exception 
     */
    @AuraEnabled
    public static Map<String, Object> settingPickListOptions( List<String> purchasePickListFiledName, List<String> purchaseItemPickListFiledName){
        Map<String, Object> resultMap = new Map<String, Object>();
        try {
            gfUtilController utilContoller = new gfUtilController();
            resultMap = new Map<String, Object> {
                PURCHASE_ORDER_OBJECT_NAME => utilContoller.getPickListOptions(PURCHASE_ORDER_OBJECT_NAME, purchasePickListFiledName),
                PURCHASE_ORDER_LINE_ITEM_OBJECT_NAME => utilContoller.getPickListOptions(PURCHASE_ORDER_LINE_ITEM_OBJECT_NAME, purchaseItemPickListFiledName)
            };
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return resultMap;
    }

    /**
     * 데이터 수정 화면 저장된 데이터 불러오는 메서드
     * @param {String} objectName 
     * @param {List<String>} pickListFieldName 
     * @return  `Map<String, Object>`
     * @exception 
     */
    @AuraEnabled
    public static OrderInfoWrapperClass initRecord(String recordId) {
        OrderInfoWrapperClass resultList = new OrderInfoWrapperClass();
        try {
            PurchaseOrder__c order = [SELECT Id, Name, OrderDate__c, PurchaseVendor__c, 
                                             RequestDate__c, OrderType__c, PartnerId__c,
                                            ZipCode__c,Address__c, RestofAddress__c, 
                                            RequestedBy__c, SpecialTerms__c 
                                      FROM PurchaseOrder__c 
                                      WHERE Id = :recordId
                                    ];
            resultList = new OrderInfoWrapperClass(order);
            
           for(PurchaseOrderLineItem__c item : [SELECT Id, ProductCode__c, ProductId__c, Quantity__c, Tax_Type__c,
                                                       ProductId__r.Name, Unit__c, UnitPrice__c, TotalAmount__c, TaxRate__c,
                                                       SkuOption1__c, SkuOption2__c, SkuOption3__c, PurchaseOrder__c 
                                                FROM PurchaseOrderLineItem__c WHERE PurchaseOrder__c = :recordId]) 
            {
                resultList.itemList.add(new OrderInfoItemWrapperClass(item));
            }     
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return resultList;
    }

    /**
     * 데이터 저장 메서드
     * @param {String} record 
     * @exception 
     */
    @AuraEnabled
    public static String insertRecord(String record){
        String result;
        try {
            GfCreatePurchaseOrderModalController modalController = new GfCreatePurchaseOrderModalController();
            OrderInfoWrapperClass orderInfo = (OrderInfoWrapperClass)JSON.deserialize(record, OrderInfoWrapperClass.class);
            PurchaseOrder__c purchaseOrder = modalController.convertObjectType(orderInfo);
            insert purchaseOrder;

            List<PurchaseOrderLineItem__c> orderItemList = new List<PurchaseOrderLineItem__c>();
            for(OrderInfoItemWrapperClass item : orderInfo.itemList) {
                PurchaseOrderLineItem__c lineItem = modalController.convertObjectType(item);
                lineItem.PurchaseOrder__c         = purchaseOrder.Id;
                orderItemList.add(lineItem);
            }

            insert orderItemList;

            result = purchaseOrder.Id;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return result;
    }

    /**
     * 데이터 저장 메서드
     * @param {String} record 
     * @exception 
     */
    @AuraEnabled
    public static Map<String, Object> editRecord(String record, List<Id> deleteIdList){
        Map<String, Object> resultMap = new Map<String, Object>();
        Savepoint sp = Database.setSavepoint();
        try {
            GfCreatePurchaseOrderModalController modalController = new GfCreatePurchaseOrderModalController();
            OrderInfoWrapperClass orderInfo = (OrderInfoWrapperClass)JSON.deserialize(record, OrderInfoWrapperClass.class);
            PurchaseOrder__c purchaseOrder = modalController.convertObjectType(orderInfo);
            update purchaseOrder;

            List<PurchaseOrderLineItem__c> orderItemList = new List<PurchaseOrderLineItem__c>();
            for(OrderInfoItemWrapperClass item : orderInfo.itemList) {
                PurchaseOrderLineItem__c lineItem = modalController.convertObjectType(item);
                if(lineItem.Id == null) {
                   lineItem.PurchaseOrder__c = purchaseOrder.Id;
                }
                orderItemList.add(lineItem);
            }
            upsert orderItemList;
            
            if(deleteIdList.size() > 0) {
                if(deleteIdList != null) {
                    Database.DeleteResult[] drList = Database.delete(deleteIdList, false);
                    for(Database.DeleteResult dr : drList) {
                        if (dr.isSuccess()) {
                            resultMap.put('isSuccess', purchaseOrder.Id);
                        }
                        else {           
                            for(Database.Error err : dr.getErrors()) {
                                String errorMsg = err.getStatusCode() + ':' +  err.getFields() + ': ' + err.getMessage();
                                resultMap.put('errorMsg', errorMsg);
                                Database.rollback(sp);
                            }
                        }
                    }
                }
            }else {
                resultMap.put('isSuccess', purchaseOrder.Id);
            }
        } catch (Exception e) {
            Database.rollback(sp);
            throw new AuraHandledException(e.getMessage());
        }
        return resultMap;
    }

    /**
     * 레코트를 PurchaseOrder__c 오브젝트 형식으로 변형 하는 메서드
     */
    private PurchaseOrder__c convertObjectType(OrderInfoWrapperClass record) {
        PurchaseOrder__c purchaseOrder = new PurchaseOrder__c();
        if(record != null) {
            purchaseOrder.Id                      = record.id;
            purchaseOrder.Name                    = record.orderNumber;
            purchaseOrder.ZipCode__c              = record.zipCode;
            purchaseOrder.Address__c              = record.address;
            purchaseOrder.RestofAddress__c        = record.addressDetail;
            purchaseOrder.RequestedBy__c          = record.registor;
            purchaseOrder.SpecialTerms__c         = record.description;
            purchaseOrder.RequestDate__c          = record.requestDate;
            purchaseOrder.OrderDate__c            = record.purchaseDate;
            purchaseOrder.PurchaseVendor__c       = String.isNotBlank(record.purchaseVender) ? record.purchaseVender : null;
            purchaseOrder.PartnerId__c            = String.isNotBlank(record.partnerId) ? record.partnerId : null;
        }
        return purchaseOrder;
    }

    /**
     * 레코트를 PurchaseOrderLineItem__c 오브젝트 형식으로 변형 하는 메서드
     */
    private PurchaseOrderLineItem__c convertObjectType(OrderInfoItemWrapperClass record) {
        PurchaseOrderLineItem__c purchaseItem = new PurchaseOrderLineItem__c();          
        if(record != null) {
            purchaseItem.Id                     = record.id;
            purchaseItem.ProductId__c           = record.productId;
            purchaseItem.Quantity__c            = record.quantity;
            purchaseItem.Unit__c                = record.unit;
            purchaseItem.UnitPrice__c           = record.productPrice;
            purchaseItem.SkuOption1__c          = record.color;
            purchaseItem.SkuOption2__c          = record.size;
            purchaseItem.SkuOption3__c          = record.material;
            purchaseItem.Tax_Type__c            = record.taxType;
            purchaseItem.TaxRate__c             = record.taxRate;
           // purchaseItem.PurchaseOrder__c       = String.isNotBlank(record.purchaseOrder) ? record.purchaseOrder  : null;
        }
        return purchaseItem;
    }

    public class OrderInfoWrapperClass {
        @AuraEnabled public String id;
        @AuraEnabled public String orderNumber;
        @AuraEnabled public String purchaseVender;
        @AuraEnabled public String partnerId;
        @AuraEnabled public Date requestDate;
        @AuraEnabled public Date purchaseDate;
        @AuraEnabled public String orderType;
        @AuraEnabled public String zipCode;
        @AuraEnabled public String address;
        @AuraEnabled public String addressDetail;
        @AuraEnabled public String registor;
        @AuraEnabled public String description;
        @AuraEnabled public List<OrderInfoItemWrapperClass> itemList;

        public OrderInfoWrapperClass() {}

        public OrderInfoWrapperClass(PurchaseOrder__c record) {
            id              = record.Id;
            orderNumber     = record.Name;
            purchaseDate    = record.OrderDate__c;
            purchaseVender  = record.PurchaseVendor__c;
            partnerId       = record.PartnerId__c;
            requestDate     = record.RequestDate__c;
            orderType       = record.OrderType__c;
            zipCode         = record.ZipCode__c;
            address         = record.Address__c;
            addressDetail   = record.RestofAddress__c;
            registor        = record.RequestedBy__c;
            description     = record.SpecialTerms__c;
            itemList = new List<OrderInfoItemWrapperClass>();
        }

    }

    public class OrderInfoItemWrapperClass {
        @AuraEnabled public String id;
        @AuraEnabled public String productId;
        @AuraEnabled public String productName;
        @AuraEnabled public String productCode;
        @AuraEnabled public String productUrl; 
        @AuraEnabled public Decimal quantity;
        @AuraEnabled public Decimal productPrice;
        @AuraEnabled public String totalPrice;
        @AuraEnabled public Double taxRate;
        @AuraEnabled public String unit;
        @AuraEnabled public String taxType;
        @AuraEnabled public String color;
        @AuraEnabled public String size;
        @AuraEnabled public String material;
        @AuraEnabled public String purchaseOrder;

        public OrderInfoItemWrapperClass() {

        }

        public OrderInfoItemWrapperClass(PurchaseOrderLineItem__c record) {
            this.id             = record.Id;
            this.productId      = record.ProductId__c;
            this.productName    = String.isNotBlank(record.ProductId__c) ? record.ProductId__r.Name : null;
            this.productCode    = record.ProductCode__c;
            this.productUrl     = makeRecordURL(record.ProductId__c);
            this.quantity       = record.Quantity__c;
            this.productPrice   = record.UnitPrice__c;
            this.totalPrice     = String.valueOf(record.TotalAmount__c);
            this.taxRate        = record.TaxRate__c;
            this.unit           = record.Unit__c;
            this.taxType        = record.Tax_Type__c;
            this.color          = record.SkuOption1__c;
            this.size           = record.SkuOption2__c;
            this.material       = record.SkuOption3__c;
            this.purchaseOrder  = record.PurchaseOrder__c;
        }

        private String makeRecordURL(Id recordId) {
            return URL.getOrgDomainURL().toExternalForm() + '/' + recordId;
        }

    }

}